"""scripts_v2

Revision ID: 2758303763dd
Revises: 992c9f1aeea8
Create Date: 2026-09-15 15:14:27.795448
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '2758303763dd'
down_revision: Union[str, None] = '992c9f1aeea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('scripts', 'createdAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('scripts', 'created_at')
    # ### end Alembic commands ###
