"""empty message

Revision ID: 4d423f233438
Revises: 
Create Date: 2026-09-11 17:52:52.832518
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4d423f233438'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='campaignstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('google_rating', sa.Float(), nullable=True),
    sa.Column('google_reviews', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('google_maps_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('opportunity_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'REPLIED', 'MEETING', 'PROPOSAL', 'CUSTOMER', 'LOST', name='leadstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('in_prospecting', sa.Boolean(), nullable=False),
    sa.Column('proposal_value', sa.Integer(), nullable=True),
    sa.Column('deal_value', sa.Integer(), nullable=True),
    sa.Column('deal_closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_maps_url')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_in_prospecting'), 'leads', ['in_prospecting'], unique=False)
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('total_found', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searches_id'), 'searches', ['id'], unique=False)
    op.create_table('website_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('has_website', sa.Boolean(), nullable=False),
    sa.Column('has_https', sa.Boolean(), nullable=False),
    sa.Column('has_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('has_instagram', sa.Boolean(), nullable=False),
    sa.Column('has_form', sa.Boolean(), nullable=False),
    sa.Column('has_budget_cta', sa.Boolean(), nullable=False),
    sa.Column('has_phone_on_site', sa.Boolean(), nullable=False),
    sa.Column('is_custom_domain', sa.Boolean(), nullable=False),
    sa.Column('site_status', sa.String(), nullable=True),
    sa.Column('keywords_found', sa.Text(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_analyses_id'), 'website_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_website_analyses_website_url'), 'website_analyses', ['website_url'], unique=True)
    op.create_table('campaign_lead',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'lead_id')
    )
    op.create_table('search_lead',
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('search_id', 'lead_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_lead')
    op.drop_table('campaign_lead')
    op.drop_index(op.f('ix_website_analyses_website_url'), table_name='website_analyses')
    op.drop_index(op.f('ix_website_analyses_id'), table_name='website_analyses')
    op.drop_table('website_analyses')
    op.drop_index(op.f('ix_searches_id'), table_name='searches')
    op.drop_table('searches')
    op.drop_index(op.f('ix_leads_in_prospecting'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
