"""scripts

Revision ID: 992c9f1aeea8
Revises: 4d423f233438
Create Date: 2026-09-15 14:23:52.758232
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '992c9f1aeea8'
down_revision: Union[str, None] = '4d423f233438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('WHATSAPP', 'EMAIL', 'COLD_CALL', 'INSTAGRAM', name='scriptcategory'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_id'), 'scripts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scripts_id'), table_name='scripts')
    op.drop_table('scripts')
    # ### end Alembic commands ###
